config/routes.rb
Weblog40::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks:"omniauth_callbacks" } do
    get '/users/auth/:provider' => "omniauth_callbacks#passthru"
  end

  resources :authentications

  resources :posts do
    resources :comments
  end

  namespace :admin do
	root :to => "base#index"
    resources :users
    resources :groups
  end

  root :to => "posts#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :title, :blog, :draft
  has_many :comments
  has_and_belongs_to_many :groups

  validates :title, :presence => true
  validates :blog, :presence => true

  scope :readable_by, lambda { |user| 
    if user && user.admin?
      #anything goes
    elsif user
      joins('LEFT OUTER JOIN "groups_posts" ON "groups_posts"."post_id" = "posts"."id" LEFT OUTER JOIN "groups" ON "groups"."id" = "groups_posts"."group_id" LEFT OUTER JOIN "users" ON "users"."group_id" = "groups"."id"').
        where(['posts.draft = ? AND (users.id = ? OR users.id IS NULL)', false, user.id]).
        select("DISTINCT 'posts'.*")
    else #public user
      joins('LEFT OUTER JOIN "groups_posts" ON "groups_posts"."post_id" = "posts"."id"').where(:draft => false, :groups_posts => {:group_id => nil})
    end
  }

  def method_missing(m, *args, &block)
    if [:day, :month, :year].include? m
      [created_at, updated_at].max.send(m)
    else
      super(m, *args, &block)
    end
  end

  def full_post
    "# #{title}\n\n#{blog}"
  end

  def abstract
    words = blog.scan(/\S+/)
    sentances_found = 0
    words.take_while { |word| keep = (sentances_found < 2); sentances_found += 1 if word =~ /\./; keep }
    words[0...30].join(' ')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :authorize_admin, :except => [:index, :show]
  before_filter :grab_post, :only => [:show, :edit, :update, :destroy]
  before_filter :grab_groups, :enly => [:new, :edit]
  
  def index
    @posts = Post.readable_by(current_user).all
    if params[:q]
      render "posts/index_listing"
    else
      render "posts/index"
    end
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params[:post])
    group_ids = params[:group][:group_id] if params[:group]
    @post.groups = Group.find(group_ids) unless !group_ids || group_ids.empty?
    if @post.save
      flash[:notice] = "Post has been created."
      redirect_to @post
    else
      flash[:alert] = "Post has not been created."
      render action:"new"
    end
  end

  def show
  end
  
  def edit
  end

  def update
    if @post.update_attributes(params[:post])
      flash[:notice]= "Post has been updated."
      redirect_to @post
    else
      flash[:alert]= "Post has not been updated."
      render action:"edit"
    end
  end

  def destroy
    @post.destroy
    flash[:notice] = "Post has been deleted."
    redirect_to posts_path
  end

  private
  def grab_post
    if params[:id].numeric?
      @post = Post.readable_by(current_user).find(params[:id])
    else
      @post = Post.readable_by(current_user).find_by_title!(params[:id])
    end

  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The post you were looking for could not be found."
    redirect_to posts_path
  end

  def grab_groups
    @groups = Group.all
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  class ColorizedCodeHTML < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language) 
    end
  end

  class AbstractHTML < Redcarpet::Render::HTML
    def header(text, header_level)
      ""
    end

    def image(link, title, alt_text)
      ""
    end

    def autolink(link, link_type)
      ""
    end

    def link(link, title, alt_text)
      ""
    end
  end

  def abstract_markdown(source)
    markdown_options = [:no_intra_emphasis, :fenced_code_blocks, :lax_html_blocks].each_with_object({}) { |option, h| h[option] = true }
    render_options = [:hard_wrap].each_with_object({}) { |option, h| h[option] = true }
    converter = Redcarpet::Markdown.new(AbstractHTML.new(render_options), markdown_options)
    converter.render(source).html_safe
  end

  def markdown(source)
    markdown_options = [:no_intra_emphasis, :tables, :fenced_code_blocks, :lax_html_blocks, :autolink, :strikethrough, :superscript].each_with_object({}) { |option, h| h[option] = true }
    render_options = [:hard_wrap].each_with_object({}) { |option, h| h[option] = true }
    converter = Redcarpet::Markdown.new(ColorizedCodeHTML.new(render_options), markdown_options)
    converter.render(source).html_safe
  end
end

app/views/posts/_form.html.haml
%section#create
  = form_for(@post) do |f|
    = f.error_messages
    %p
      = f.label :title
      = f.text_field :title
    %p
      = f.check_box :draft
      = f.label :draft
    %p
      = f.label :blog
      %br
      %div#wmd-panel
        %div#wmd-button-bar
        = f.text_area :blog, {id:'wmd-input'}
    %p
      = "Assign to groups"
      %ul
        - @groups.each do |group|
          %li
            = check_box_tag "group[group_id][]", group.id, @post.groups.include?(group), {id:"group_#{group.id}"}
            = label_tag "group_#{group.id}", group.name

    = f.submit

%section#preview
  %div#wmd-preview


:javascript
  (function() {
    var converter = Markdown.getSanitizingConverter();
    var editor = new Markdown.Editor(converter);
    editor.run();
  })();

app/views/posts/edit.html.haml
- content_for :header do
  = javascript_include_tag "Markdown.Converter.js", "Markdown.Sanitizer.js", "Markdown.Editor.js"
  
%h2= "Edit Post - #{@post.title}"
= render "form"

app/views/posts/index.html.haml
= admins_only do
  = link_to 'New Post', new_post_path

%section#full_articles
  - @posts[0..2].try(:each) do |post|
    %ul
      %li
        %date
          %span.day= post.day
          %span.month= post.month
          %span.year= post.year
        %p= link_to post.title, post
        %p= markdown(post.full_post)

%section#preview
  - @posts[2...5].try(:each) do |post|
    %ul
      %li
        %date
          %span.day= post.day
          %span.month= post.month
          %span.year= post.year
        %h1= link_to post.title, post
        %p= markdown(post.abstract)
        %p= link_to "read more", post

app/views/posts/index_listing.html.haml
= admins_only do
  = link_to 'New Post', new_post_path

- @posts.group_by{|p| p.month_year}.each do |monthyear, posts|
  %ul
    %li=monthyear
      =posts.each do |post|
        %ul
          %li= link_to post.title, post
            %p= post.short_abstract

app/views/posts/new.html.haml
- content_for :header do
  = javascript_include_tag "Markdown.Converter.js", "Markdown.Sanitizer.js", "Markdown.Editor.js"

= render 'form'

app/views/posts/show.html.haml
- draft = @post.draft ? " Draft":""
%article
  %h2= @post.title + draft
  = markdown(@post.blog)

= admins_only do
  - if @post.groups.empty?
    = "Viewable by everyone"
  - else
    = "Viewable by groups #{@post.groups.map(&:name).join(", ")}"

%menu
  = link_to "Add Comment", new_post_comment_path(@post)
  = admins_only do
    = link_to "Edit", edit_post_path(@post)
    = link_to "Delete", @project, :method => :delete, :confirm => "Are you sure you want to delete this project?"