config/routes.rb
Weblog40::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks:"omniauth_callbacks" } do
    get '/users/auth/:provider' => "omniauth_callbacks#passthru"
  end

  resources :authentications

  resources :posts do
    resources :comments
  end

  namespace :admin do
	root :to => "base#index"
    resources :users
    resources :groups
  end

  root :to => "posts#index"

end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :users
  has_and_belongs_to_many :posts
  validates :name, presence:true, uniqueness:true 
end

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < Admin::BaseController
  before_filter :find_group, :only => [:show, :edit, :update, :destroy]
  before_filter :find_users, :only => [:new, :edit]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def show
  end

  def edit
  end

  def update
    @group.update_attributes(params[:group])
    user_ids = params[:user][:user_id] if params[:user]
    @group.users = User.find(user_ids) unless !user_ids || user_ids.empty?

    if @group.save
      flash[:notice] = "Group has been updated."
      redirect_to admin_groups_path
    else
      flash[:alert] = "Group has not been updated."
      render :action => "edit"
    end
  end

  def create
    @group = Group.create(params[:group]);
    user_ids = params[:user][:user_id] if params[:user]
    @group.users = User.find(user_ids) unless !user_ids || user_ids.empty?

    if @group.save
      flash[:notice] = "Group has been created."
      redirect_to admin_groups_path
    else
      flash[:alert] = "Group has not been created."
      render :action => "new"
    end
  end

	private
	def find_group
		@group = Group.find(params[:id])
	end

    def find_users
      @users = User.all
    end
end

app/helpers/admin/groups_helper.rb
module Admin::GroupsHelper
end

app/views/admin/groups/_form.html.haml
= form_for [:admin, @group] do |f|
  = f.error_messages
  %p
    = f.label :name
    = f.text_field :name

  - if @users
    - @users.each do |user|
      = check_box_tag "user[user_id][]", user.id, @group.users.include?(user), {:id=>"user_#{user.id}"}
      = label_tag "user_#{user.id}", user.email

  = f.submit

app/views/admin/groups/edit.html.haml
= render "form"

app/views/admin/groups/index.html.haml
= link_to "New Group", new_admin_group_path
%ul.groups
  - if @groups
    - @groups.each do |group|
      %li 
        = link_to group.name, [:admin, group]
        %ul.users
          - group.users.each do |user|
            %li= user.email

app/views/admin/groups/new.html.haml
= render "form"

app/views/admin/groups/show.html.haml
%h1= @group.name

%h2= "Members"
%ul
  - @group.users.each do |user|
    %li= user.email

= link_to "Edit", edit_admin_group_path(@group) 