config/routes.rb
Weblog40::Application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks:"omniauth_callbacks" } do
    get '/users/auth/:provider' => "omniauth_callbacks#passthru"
  end

  resources :authentications

  resources :posts do
    resources :comments
  end

  namespace :admin do
	root :to => "base#index"
    resources :users
    resources :groups
  end

  root :to => "posts#index"

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield :title 
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tag
    = yield :header

  %body
    #container
      %nav
        %ul
          = admins_only do
            %li= link_to_unless_current "Admin", admin_root_path

          - if !user_signed_in?
            %li= link_to_unless_current "Sign in", new_authentication_path
          - else
            %li= link_to_unless_current "Account", authentications_path
            %li= link_to "Sign out", destroy_user_session_path
            %li.identifier= "Signed in as #{current_user.email}"

      %header
        %h1 Blog Title
        %nav#find
          %ul
            !!!%li
            !!!  =form_for :posts do |f|
            !!!    %label Search
            !!!    = field :search

            %li= link_to "Home", posts_path
            %li= link_to_unless_current "Archives", posts_path(q:"all")
            = admins_only do
              = yield :links

      %section#main
        %section#content
          #notifications
            - flash.each do |key, value|
              %div.flash{:id => "#{key}"} 
                = value
          
          = yield

      %footer
        %h1 All rights reserved